### PR TITLE
fixed Google Maps API compatibility error

### PR DESCRIPTION
**Pull request by subin216**
fixed Google Maps API compatibility error

### CODE REVIEW

**Comment by jleung51** [comment]
This is related to issue #28.

**Comment by jleung51** [comment]
The application is currently crashing for me with the new change unfortunately.

# Steps to Reproduce

1. Build the updated app
2. Launch the app
3. Select either the Pacman or Ghost spectator mode
4. Enter the Spectator mode

# Results

```
E/AndroidRuntime: FATAL EXCEPTION: Thread-8
    Process: ca.sfu.pacmacro, PID: 14960
    java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/ProtocolVersion;
        at gu.b(:com.google.android.gms.dynamite_mapsdynamite@17122081@17.1.22 (100400-245988633):3)
        at gr.a(:com.google.android.gms.dynamite_mapsdynamite@17122081@17.1.22 (100400-245988633):3)
        at gt.a(:com.google.android.gms.dynamite_mapsdynamite@17122081@17.1.22 (100400-245988633):14)
        at com.google.maps.api.android.lib6.drd.ak.a(:com.google.android.gms.dynamite_mapsdynamite@17122081@17.1.22 (100400-245988633):4)
        at fv.a(:com.google.android.gms.dynamite_mapsdynamite@17122081@17.1.22 (100400-245988633):22)
        at fv.run(:com.google.android.gms.dynamite_mapsdynamite@17122081@17.1.22 (100400-245988633):8)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.ProtocolVersion" on path: DexPathList[[zip file "/data/user_de/0/com.google.android.gms/app_chimera/m/000000ca/MapsDynamite.apk"],nativeLibraryDirectories=[/data/user_de/0/com.google.android.gms/app_chimera/m/000000ca/MapsDynamite.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at ab.loadClass(:com.google.android.gms.dynamite_dynamiteloader@17122081@17.1.22 (100400-245988633):4)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at gu.b(:com.google.android.gms.dynamite_mapsdynamite@17122081@17.1.22 (100400-245988633):3) 
        at gr.a(:com.google.android.gms.dynamite_mapsdynamite@17122081@17.1.22 (100400-245988633):3) 
        at gt.a(:com.google.android.gms.dynamite_mapsdynamite@17122081@17.1.22 (100400-245988633):14) 
        at com.google.maps.api.android.lib6.drd.ak.a(:com.google.android.gms.dynamite_mapsdynamite@17122081@17.1.22 (100400-245988633):4) 
        at fv.a(:com.google.android.gms.dynamite_mapsdynamite@17122081@17.1.22 (100400-245988633):22) 
        at fv.run(:com.google.android.gms.dynamite_mapsdynamite@17122081@17.1.22 (100400-245988633):8) 
I/chatty: uid=10209(ca.sfu.pacmacro) identical 3 lines
V/PelletManager: Received pellet of type PILL
I/Process: Sending signal. PID: 14960 SIG: 9
Application terminated.
```

**Comment by subin216** [comment]
Reason: https://stackoverflow.com/questions/50461881/java-lang-noclassdeffounderrorfailed-resolution-of-lorg-apache-http-protocolve

Solution:
Added <uses-library android:name="org.apache.http.legacy" android:required="false"/> on manifest

**Comment by subin216** [comment]
Reason: https://stackoverflow.com/questions/50461881/java-lang-noclassdeffounderrorfailed-resolution-of-lorg-apache-http-protocolve

Solution:
Added <uses-library android:name="org.apache.http.legacy" android:required="false"/> on manifest

**Comment by subin216** [comment]
Reason: https://stackoverflow.com/questions/50461881/java-lang-noclassdeffounderrorfailed-resolution-of-lorg-apache-http-protocolve

Solution:
Added uses-library android:name="org.apache.http.legacy" on manifest

**Comment by subin216** [comment]
Reason: https://stackoverflow.com/questions/50461881/java-lang-noclassdeffounderrorfailed-resolution-of-lorg-apache-http-protocolve

Solution:
Added uses-library android:name="org.apache.http.legacy" on manifest

**Comment by subin216** [comment]
fixed side effects caused by changing sdk version to 28

**Review by jleung51 — APPROVED** [review]
Approved, thanks for the changes!

**Pull request merged**
